# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rsec < Formula
  desc "Simple, powerful, and secure secret management for your applications"
  homepage "https://github.com/runsecret/rsec"
  version "0.3.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runsecret/rsec/releases/download/v0.3.13/rsec_Darwin_x86_64.tar.gz"
      sha256 "bfc26cc366ca813a47b785f6247e7ce7a556ca273fbe4e6ef6e5440cacb052f7"

      def install
        bin.install "rsec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runsecret/rsec/releases/download/v0.3.13/rsec_Darwin_arm64.tar.gz"
      sha256 "248db7fab0061ab3253926cb1bd7391531405033bab16f203a4cb1073c33cbdd"

      def install
        bin.install "rsec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/runsecret/rsec/releases/download/v0.3.13/rsec_Linux_x86_64.tar.gz"
        sha256 "4e0363f03312083bc3b16da657bf2379477f50ed09345b34cf507d82af04eb0d"

        def install
          bin.install "rsec"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/runsecret/rsec/releases/download/v0.3.13/rsec_Linux_arm64.tar.gz"
        sha256 "3b77cd0a1ad0eacd3549276b9c20d818e3945c57ae0150e581a481cf04ef52dd"

        def install
          bin.install "rsec"
        end
      end
    end
  end
end
