# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rsec < Formula
  desc "Simple, powerful, and secure secret management for your applications."
  homepage ""
  version "0.3.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runsecret/rsec/releases/download/v0.3.7/rsec_Darwin_x86_64.tar.gz"
      sha256 "0c4ac5317e1806fae4fe41493393b2452a9fa25e88de5dbb619e93e424552154"

      def install
        bin.install "rsec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runsecret/rsec/releases/download/v0.3.7/rsec_Darwin_arm64.tar.gz"
      sha256 "870127f53880ec298fb735b70b6366190ace611a81d6dae50272dd08fa4f977e"

      def install
        bin.install "rsec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/runsecret/rsec/releases/download/v0.3.7/rsec_Linux_x86_64.tar.gz"
        sha256 "af86ea77114d0d8434fee8481a00f0bc2f0c60256d08c578cf977f748103ef00"

        def install
          bin.install "rsec"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/runsecret/rsec/releases/download/v0.3.7/rsec_Linux_arm64.tar.gz"
        sha256 "205ae43a2a3840481b80a63cd2d0928e66630be21707c45ed596814b3304683d"

        def install
          bin.install "rsec"
        end
      end
    end
  end
end
